# Generated by Django 4.2.4 on 2023-08-12 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customerservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='attachment',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='problem',
            name='user',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
