# Generated by Django 4.2.4 on 2023-08-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0004_problem_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='attachment',
            field=models.FileField(blank=True, upload_to='attachments'),
        ),
    ]
